# Site settings
title: Peter Siemens
email: peterjsiemens@gmail.com
description: I make things with wood, metal, fabric and code in Squamish, BC.
baseurl: ""
url: "http://petersiemens.com"
instagram_username: psiemens
github_username: psiemens

# Build settings
markdown: kramdown
